Refactor/#29 깃허브 , 카카오 소셜로그인 구현
Team13-MoaMoa/frontend pull request #38
Opened 2023-10-07 18:59 UTC by Leeseunghwan7305

## 📖 개요
## 💻 작업사항
-  카카오 , 깃허브 소셜로그인 구현
- 최초 회원 추가정보 입력 후 회원가입시 다시 로그인을 해야하게 수정

## 💡 작성한 이슈 외에 작업한 사항

##  수정사항
-  authInstance 재설정
## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2023-10-10 09:02 UTC, sangminlee98 requested changes

2023-10-10 09:02 UTC, sangminlee98 commented on src/api/axiosCustom.ts
> +
혹시 authInstance와 createAuthInstacne 두개를 따로 둔 이유가 있을까요??
로그인 성공 후 token값이 어차피 true가 되어서 따로 createAuthInstance를 쓰지 않아도 괜찮을 것 같아요!

2023-10-10 09:02 UTC, sangminlee98 commented on src/api/logout.ts
> +  createAuthInstance(token);
createAuthInstance를 해주지 않아도 authInstance에서 헤더에서 토큰이 있다면 header에 토큰을 담아서 보내주는 것 같습니다!

2023-10-10 09:02 UTC, sangminlee98 commented on src/api/userAuth.ts
> +  let res = await baseInstance.get(`login/oauth2/code/${auth}?code=${code}`);
사소한건데 변수선언을 let보다 const로 통일해줘도 괜찮을 것 같습니다!

2023-10-10 09:02 UTC, sangminlee98 commented on src/pages/callback/github/index.tsx
> +      }
callback url이 github인데 kakao값이 올 수도 있나요 ??

2023-10-10 09:02 UTC, sangminlee98 commented on src/pages/callback/github/index.tsx
> +        createAuthInstance(token);
위 리뷰랑 마찬가지로 createAuthInstance는 없어도 괜찮을 것 같아요!

2023-10-10 09:02 UTC, sangminlee98 commented on src/pages/callback/kakao/index.tsx
> +    })();
callback/github와 동일한 리뷰입니다!

2023-10-10 09:02 UTC, sangminlee98 commented on src/components/Login/login4.tsx
> +
가입완료 버튼을 눌러도 메인페이지로 이동되지 않습니다!
사용자가 새로고침을 해야되는데, 코드상에서 처리해주실 수 있을까요?

2023-10-10 09:08 UTC, Leeseunghwan7305 commented on src/api/axiosCustom.ts
> +
저도 처음에 authInstance 하나만 썻었는데 
 제 예상은 로그인하거나 로그아웃할때 토큰을 받거나 삭제되는걸 생각했습니다.
근데 토큰이 새로고침이 안되면서 header에 토큰이 안실려들어가더라구요..!
그래서 createAuthInstance를 따로 만들어서 로그인또는 로그아웃을 할 때 선언을 해주면서 header안에 토큰을 넣어주었습니다 !

2023-10-10 09:09 UTC, Leeseunghwan7305 commented on src/api/logout.ts
> +  createAuthInstance(token);
위에 리뷰처럼 로그아웃하면 localstroage에 토크을 삭제하고 header에 토큰이 실리지않게하고 싶었는데 초기화가 안되는 이슈가 있어서 
createAuthInstance 함수를 선언해주어서 새로고침을 시켯습니다 !

2023-10-10 09:09 UTC, Leeseunghwan7305 commented on src/api/userAuth.ts
> +  let res = await baseInstance.get(`login/oauth2/code/${auth}?code=${code}`);
수정하겠습니다 !

2023-10-10 09:09 UTC, Leeseunghwan7305 commented on src/pages/callback/github/index.tsx
> +      }
아 절대 올 수 없는데 수정하겠습니다 !

2023-10-10 09:10 UTC, Leeseunghwan7305 commented on src/pages/callback/github/index.tsx
> +        createAuthInstance(token);
위 리뷰와 동일합니다 !

2023-10-10 09:10 UTC, Leeseunghwan7305 commented on src/pages/callback/kakao/index.tsx
> +    })();
수정하겠습니다 !

2023-10-11 17:55 UTC, Leeseunghwan7305 commented on src/api/axiosCustom.ts
> +
authInstance.interceptors.request.use((config) => {
  if (typeof window === 'object') {
    const accesstoken = localStorage.getItem('access_token');
    config.headers['Authorization'] = `Bearer ${accesstoken}`;
  }

  return config;
});
interceptors를 활용해서 요청을 할때마다 access_token을 header에 넘겨줘서 해결했습니다 !

2023-10-12 05:22 UTC, JunJongHun requested changes
로그인 부분 잘 구현해주셧네요👍

추가적으로 **런타임 오류**가 있어서 알려드립니다!
회원가입을 할 때, 마지막 단계에서 프로필 설정하는 부분이 있습니다!
프로필 선택을 안하면 기본 이미지를 세팅하도록 해야하는데, 작동이 안됩니다. 

![스크린샷 2023-10-12 오후 1 53 52](https://github.com/Team13-MoaMoa/frontend/assets/90402926/324bb105-637d-492d-b563-f0150301b35e)
![스크린샷 2023-10-12 오후 1 54 15](https://github.com/Team13-MoaMoa/frontend/assets/90402926/7981c393-bc94-4813-92e9-5700eb7edb3c)

확인 부탁드립니다😄

2023-10-12 05:22 UTC, JunJongHun commented on next.config.js
> +  reactStrictMode: false,
`false`로 바꾸신 이유가 따로 있으신가요?!

2023-10-12 05:22 UTC, JunJongHun commented on src/api/axiosCustom.ts
> +export let authInstance = axios.create({
`const`로 수정 하는건 어떨까요? 따로 다시 재할당하는 부분이 없어 보여서요😄!

2023-10-12 05:22 UTC, JunJongHun commented on src/api/logout.ts
> +export const logoutApi = async (auth_provider: string) => {
auth_provider의 type을 `string`이 아닌 Literal type으로 정의하면 실수 방지와 오류를 사전에 방지하는데 도움이 될 것 같아요!

따라서, 추가적으로 정의해주시면 좋겠습니다😄

2023-10-12 05:22 UTC, JunJongHun commented on src/api/logout.ts
> +    registrationId: typeof window === 'object' ? auth_provider : '',
@Leeseunghwan7305 @sangminlee98 @wisdomyeon 
개인적으로 빈 문자열보다는 `null`을 사용해서 값이 의도적으로 비어있음을 표현하는건 어떨까요?

또는 `accessToken: typeof window === 'object' && token` 이런식도 좋아보이는데 의견 부탁드려요😄

2023-10-12 05:22 UTC, JunJongHun commented on src/api/signUp.ts
> +  auth_provider: string;
위에 Literal type 부분 리뷰와 같습니다!

2023-10-12 05:22 UTC, JunJongHun commented on src/api/signUp.ts
> +  const res = await baseInstance.post('api/v1/users/signup', newUser);
'api/v1/users/signup' 부분에서 저희 'api/v1'은 따로 상수화 시켜 놓는게 어떨까요?

사실 추가적으로 바뀔 가능성은 적다고 판단 되지만, 버전에 따라 관리 할 수도 있고 추가적으로 생길 수 있다고 생각합니다! 유지보수를 위해서 좋다고 생각해요😄

2023-10-12 05:22 UTC, JunJongHun commented on src/components/Loading/index.tsx
> +        <Image fill src={loadingUI} alt="" />
alt 값 넣어주면 좋을 것 같아요!

2023-10-12 05:22 UTC, JunJongHun commented on src/components/Login/index.tsx
> +
로직이 중복되어 보이는데 함수화 해서 재사용성을 높이는 방법도 좋아보여요!
KEY 값을 인자로 받고 함수를 정의한다면 추후에 다른 로그인 방법이 생겨도 활용 가능해 보입니다😄

2023-10-12 05:22 UTC, JunJongHun commented on src/store/user.ts
> +    auth_provider: string;
literal type 리뷰와 같습니다!

2023-10-12 06:57 UTC, Leeseunghwan7305 commented on next.config.js
> +  reactStrictMode: false,
개발모드일때 api요청을 보내면 두번씩 요청 되어서 로그인에러가 나오더라구요 ,,
false로 바꾸니까 잘되어서 변경했습니다 !

2023-10-12 06:57 UTC, Leeseunghwan7305 commented on src/api/axiosCustom.ts
> +export let authInstance = axios.create({
수정했습니다 !

2023-10-12 06:58 UTC, Leeseunghwan7305 commented on src/api/logout.ts
> +export const logoutApi = async (auth_provider: string) => {
엇 그렇네요  Literal type으로 정의해두면 가독성도 좋아지고 실수도 방지할 수 있을 것 같네요!

2023-10-12 06:59 UTC, Leeseunghwan7305 commented on src/api/logout.ts
> +    registrationId: typeof window === 'object' ? auth_provider : '',
accessToken: typeof window === 'object' && token 생각 못했는데 이렇게 변경하겠습니다 !
더 깔끔해진거같네요 ..!

2023-10-12 07:00 UTC, Leeseunghwan7305 commented on src/api/signUp.ts
> +  auth_provider: string;
수정했습니다 !

2023-10-12 07:04 UTC, Leeseunghwan7305 commented on src/api/signUp.ts
> +  const res = await baseInstance.post('api/v1/users/signup', newUser);
사실 swagger에서 로그인 관련된건 api/v1이 안붙어있고 다른건 붙어있어서 
처음 설계를 api 요청을 보낼 때 token이 필요한 요청은 authInstance ,  필요하지 않은 요청은 baseInstance로 나누었었는데 

위 처럼 회원가입 api는 token이 필요하지않으면서 로그인 관련 api 더라구요 그래서 api/v1을 붙이지않고 BASE_URL을 설정했었는데
저 부분만 따로 변수화해서 수정하겠습니다 !

2023-10-12 07:04 UTC, Leeseunghwan7305 commented on src/components/Loading/index.tsx
> +        <Image fill src={loadingUI} alt="" />
수정했습니다 !

2023-10-12 07:05 UTC, Leeseunghwan7305 commented on src/components/Login/index.tsx
> +
확실히 이부분을 함수화하면 추후에 로그인 방법이 많아졌을때 더 깔끔해 보이겠네요!

2023-10-12 07:05 UTC, Leeseunghwan7305 commented on src/store/user.ts
> +    auth_provider: string;
수정했습니다 !

2023-10-12 12:25 UTC, JunJongHun approved these changes

2023-10-12 12:25 UTC, JunJongHun commented on src/api/logout.ts
> +export const logoutApi = async (auth_provider: 'kakao' | 'github' | '') => {
literal type 반영 해주신거 감사합니다!

현재 확인을 해보니 `auth_provider`를 사용하는 부분에 직접 literal type을 작성해 주셨어요!

따로 type을 한 곳에서 정의해서 export로 해주신 다음 import 하는게 유지보수에 좋아보입니다😄 안그러면 다른 로그인 타입이 추가 될 때, 하나 하나 찾아서 바꿔줘야 할 것 같아요😂

다른 부분도 일괄 적용 부탁 드립니다!

2023-10-12 12:25 UTC, JunJongHun commented on src/api/axiosCustom.ts
> +const LOGIN_URL = 'http://43.200.45.247:8080/';
const BASE_URL = 'http://43.200.45.247:8080/';

const API_VERSION = 'api/v1/'

이게 더 괜찮아 보입니다!

근데, 문제가 authInstance가 로그인 할 때만 필요한게 아니고, 토큰이 필요한 api 요청할 때, 쓰는거라서 baseURL을 어떻게 하는게 좋을지 고민이네요..

사용하는 입장에서 편하게 쓰려면 어떻게 할지..？

---
지금 생각나는 방법은 interceptors.request에 조건을 걸어보는 방법? 이 있을 것 같은데, 판단이 잘 안 서네요😭

2023-10-12 12:25 UTC, JunJongHun commented on src/api/logout.ts
> +    registrationId: typeof window === 'object' && auth_provider,
반영 해주셔서 감사합니다!

다만, 혹시 작동 잘 하나요..? 지금 swagger 확인해보니까 type `string`이여서요..ㅎㅎ

제가 이걸 못 보고 리뷰를 남겼네요 😂

2023-10-12 12:25 UTC, JunJongHun commented on src/api/userAuth.ts
> +  const BASE_URL = 'http://43.200.45.247:8080/';
import 해서 사용하면 될 것 같아요!

2023-10-12 14:40 UTC, wisdomyeon approved these changes

2023-10-12 14:40 UTC, wisdomyeon commented on src/api/signUp.ts
> +  auth_provider: 'kakao' | 'github' | '';
auth_provider에 ''이 할당되면 어떻게 처리 되는지 알고 싶은데 관련 코드 어디에 있는지 알 수 있을까요?

2023-10-13 10:17 UTC, sangminlee98 commented on src/api/signUp.ts
> +  auth_provider: 'kakao' | 'github' | '';
저도 같은 의견입니다! 혹시 "" 타입을 넣으신 이유가 있을까요??
저는 'kakao' | 'github' 으로만 해도 괜찮을 것 같습니다!

2023-10-20 07:49 UTC, Leeseunghwan7305 commented on src/components/Login/login4.tsx
> +
수정했습니다 !

2023-10-20 07:50 UTC, Leeseunghwan7305 commented on src/api/logout.ts
> +export const logoutApi = async (auth_provider: 'kakao' | 'github' | '') => {
수정했습니다 !

2023-10-20 07:51 UTC, Leeseunghwan7305 commented on src/api/signUp.ts
> +  auth_provider: 'kakao' | 'github' | '';
"" 안쓰면 에러가 나서 "" 붙였던거같아요 !

2023-10-20 07:51 UTC, Leeseunghwan7305 commented on src/api/userAuth.ts
> +  const BASE_URL = 'http://43.200.45.247:8080/';
알겠스빈다 !

2023-10-20 08:24 UTC, JunJongHun requested changes
로그인 기능 구현하시느라 수고하셨어요!!

방금 리뷰 다시 달았습니다! 추가적으로 리뷰 반영 안된 부분들 적용 부탁드려요~😄

2023-10-20 08:24 UTC, JunJongHun commented on src/pages/index.tsx
> +  // }, []);
주석 없애도 될 것 같아요!

2023-10-20 08:27 UTC, Leeseunghwan7305 commented on src/pages/index.tsx
> +  // }, []);
수정했습니다 !

2023-10-20 08:28 UTC, Leeseunghwan7305 commented on src/api/userAuth.ts
> +  const BASE_URL = 'http://43.200.45.247:8080/';
수정했습니다 !

2023-10-20 08:28 UTC, Leeseunghwan7305 commented on src/api/logout.ts
> +    registrationId: typeof window === 'object' && auth_provider,
다행히 잘 작동하는거 같아요 !

2023-10-20 08:36 UTC, JunJongHun approved these changes

2023-10-20 10:30 UTC, sangminlee98 approved these changes
LGTM 👍

2023-10-20 10:31 UTC, merged