Feat/#4 메인페이지 UI 구현
Team13-MoaMoa/frontend pull request #6
Opened 2023-04-09 17:11 UTC by JunJongHun

## 추가한 기능 설명

- UI 구현
![image](https://user-images.githubusercontent.com/90402926/230786498-b1235aa0-5390-40fc-8bce-62f3492af0fd.png)

## 전달사항

- 반응형 구현 X
- 세부적인 디테일 구현 X
- 헤더/풋터 적용 X

<br>

## check list

- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?

2023-04-10 03:04 UTC, Leeseunghwan7305 requested changes
고생하셨습니다 !
comment 달은거 고쳐주시고 다시 pr날려주세요 !

2023-04-10 03:04 UTC, Leeseunghwan7305 commented on src/components/main/pagination/index.tsx
> +        color: #333;
안전하게 자식연산자로 바꿔주세요 !

2023-04-10 03:04 UTC, Leeseunghwan7305 commented on src/pages/index.tsx
> +        >
inline css 말고 자식연산자써서 emotion안에 넣어주세요 !

2023-04-10 03:04 UTC, Leeseunghwan7305 commented on src/pages/index.tsx
> +                    >
key값 넣어주세요 !

2023-04-10 13:31 UTC, sangminlee98 requested changes
지금은 임시로 넣었지만 기술 스택 이미지는 나중에 s3에 저장해서 쓸 거라서 그때가서 수정하면 될 것 같고
전체적으로 피그마 디자인하고 최대한 비슷하게 스타일링만 다시 디테일하게 보정하면 될 것 같습니다.

2023-04-10 13:31 UTC, sangminlee98 commented on src/components/common/BoardCardList/index.tsx
> +function BoardCardList({ boardCards }: { boardCards: any }) {
나중에 card props 타입이 정해지면 any타입 수정해주시면 될 것 같습니다

2023-04-10 13:31 UTC, sangminlee98 commented on src/components/main/pagination/index.tsx
> +`;
{}으로 감싸지 않고 바로 사용하셔도 괜찮을 거 같아요
하위 태그나 클래스 지정할 때는 &하고 자식 선택자 이용해서 코드 작성해주시면 될 것 같습니다!
그리고 .selected에 대한 스타일이 없어서 추가해주시면 될 것 같아요
아래는 예시 코드입니다.
```tsx
const PaginationContainer = styled(ReactPaginate)`
  display: flex;
  justify-content: center;
  margin-top: 20px;
  margin-bottom: 0;
  padding-left: 0;
  list-style: none;

  & > li {
    margin-right: 10px;
    border: 1px solid #ddd;
    border-radius: 4px;

    & > a {
      display: block;
      padding: 6px 12px;
      text-decoration: none;
      color: #333;

      &:hover {
        background-color: #f5f5f5;
      }

      &.active {
        background-color: #337ab7;
        color: #fff;
      }
    }
  }
  & > .selected {
    background-color: red;
  }
  & > .previous,
  & > .next {
    border: 1px solid #ddd;
    border-radius: 4px;
    display: inline-block;

    a {
      display: block;
      padding: 6px 12px;
      text-decoration: none;
      color: #333;

      &:hover {
        background-color: #f5f5f5;
      }
    }

    &.disabled {
      opacity: 0.5;
      pointer-events: none;
    }
  }
`;
```

2023-04-22 09:22 UTC, JunJongHun commented on src/components/main/pagination/index.tsx
> +        color: #333;
수정했습니다~ 감사합니다😄

2023-04-22 09:22 UTC, JunJongHun commented on src/pages/index.tsx
> +        >
훨씬 코드가 깔끔해졌어요! 감사합니다😁

2023-04-22 09:22 UTC, JunJongHun commented on src/pages/index.tsx
> +                    >
알려주셔서 감사합니다😄

2023-04-22 09:23 UTC, JunJongHun commented on src/components/common/BoardCardList/index.tsx
> +function BoardCardList({ boardCards }: { boardCards: any }) {
네 알겠습니다! 감사합니다😄

2023-04-22 09:24 UTC, JunJongHun commented on src/components/main/pagination/index.tsx
> +`;
덕분에 알아갑니다! 감사합니다😄

2023-04-22 10:23 UTC, Leeseunghwan7305 approved these changes

2023-04-22 10:23 UTC, sangminlee98 commented on src/components/common/BoardCardList/index.tsx
> +function BoardCardList({ boardCards }: { boardCards: any }) {
확인했습니다! 👍

2023-04-22 10:24 UTC, sangminlee98 commented on src/components/main/pagination/index.tsx
> +`;
이것도 확인했어요! 👍

2023-04-22 10:25 UTC, sangminlee98 approved these changes
확인했습니다!
메인페이지 너무 이쁘게 잘 구현해주셨어요👍👍👍

2023-04-22 10:33 UTC, merged